"""new fields in user table

Revision ID: 759aaa4895b2
Revises: 6bc3fa1ec58f
Create Date: 2018-12-17 13:00:29.208473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759aaa4895b2'
down_revision = '6bc3fa1ec58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_what_email_address', table_name='what')
    op.drop_index('ix_what_username', table_name='what')
    op.drop_table('what')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.create_table('what',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email_address', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=120), nullable=True),
    sa.Column('description', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_what_username', 'what', ['username'], unique=1)
    op.create_index('ix_what_email_address', 'what', ['email_address'], unique=1)
    # ### end Alembic commands ###
